apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  # The "Driver ID". This tells Kubernetes "Send this config to Envoy Gateway".
  # Other examples: istio.io/gateway-controller, networking.gke.io/gateway
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: default
spec:
  # Links to the "Hardware Spec" (GatewayClass) above
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      # allowedRoutes:
      #   namespaces:
      #     from: All  # <--- UNCOMMENT THIS to allow Cross-Namespace Routing (e.g. app-ns -> infra-ns)